import Head from "next/head";
import NavBar from "@/components/Navbar";
import { useState } from "react";
import type { ModalData } from "@/types/ModalData"
import CreateEditNoteModal from "@/components/CreateEditNoteModal";

export default function Home() {
  const [modalData, setModalData] = useState<ModalData>({ mode: 'create', show: false })
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <NavBar setModalData={setModalData}/>
        <CreateEditNoteModal modalData={modalData} setModalData={setModalData} />
      </main>
    </>
  );
}
